# Generated by Django 4.1.5 on 2023-01-25 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('srno', models.IntegerField()),
                ('quizName', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('totalMarks', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('total', models.IntegerField()),
                ('inQuiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER.quiz')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('qno', models.IntegerField()),
                ('question', models.TextField(primary_key=True, serialize=False)),
                ('opt1', models.CharField(max_length=50)),
                ('opt2', models.CharField(max_length=50)),
                ('opt3', models.CharField(max_length=50)),
                ('qtype', models.CharField(max_length=15)),
                ('ansKey', models.CharField(max_length=20)),
                ('inQuiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='anskey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenAns', models.CharField(max_length=20)),
                ('inQuiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER.quiz')),
                ('ofQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER.questions')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
